### ISSUE TITLE
Why the andrewrothstein.unarchivedeps is need ?

### ISSUE THREAD

**Issue by vhsantos** [andrewrothstein/ansible-stepca#1]
Hi,

I'm looking on your playbook and want to know why you are using this additional module ?? 

https://github.com/andrewrothstein/ansible-stepca/blob/b1e582427cdf54bb02f5e62c443e4ae8f70b1532/tasks/main.yml#L29-L31

thanks in advance.

**Comment by andrewrothstein** [comment]
the binary is distributed in an archive so u need tar, gzip, zip for the ansible.builtin.unarchive to work.

**Comment by vhsantos** [comment]
Hi and thanks.

Should the [ansible.builtin.unarchive](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/unarchive_module.html) make the same in this case ??

**Comment by andrewrothstein** [comment]
The unarchivedeps role installs the tools required by the ansible.builtin.unarchive module. See the notes [here](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/unarchive_module.html#notes)
